
#include <signal.h> /*to use signals*/
#include <stdio.h>
#include <stdlib.h>
#include <unistd.h> /*to use the alarm()*/
#include <stdint.h> /*standard integers*/

/*
 * references: 
 *     https://www.gnu.org/software/libc/manual/html_node/Handler-Returns.html
 *     https://www.gnu.org/software/libc/manual/html_node/Alarm-Signals.html
 */
/* compiled with: gcc -std=c11 -O2 -Wall -pedantic main.cpp && ./a.out

/* This flag controls termination of the main loop. */
volatile sig_atomic_t keep_going = 1;

/* The signal handler just clears the flag and re-enables itself. */
void
catch_alarm (int sig)
{
  keep_going = 0;
  signal (sig, catch_alarm);
  write(STDOUT_FILENO, "\nALARM!!!\n",10);  
  /* in the signal handlers 'write' is used instead of printf, 
 the reason is that, signal handlers run asynchronously, meaning
 that they can interrupt the program flow at any given point, so
 in a signal hanlder async-safe functions are to be used */
 /* http://man7.org/linux/man-pages/man7/signal-safety.7.html */ 
}

void
do_stuff (void)
{
  static uint16_t counter = 0;
  printf("%d: Doing stuff while waiting for alarm....\n", counter);
  ++counter;
}

int
main (void)
{
  /* Establish a handler for SIGALRM signals. */
  /* This SIGALRM signal typically indicates expiration of a timer that measures real or clock time.*/
  signal (SIGALRM, catch_alarm);

  /* Set an alarm to go off in a little while. */
  //alarm (2);
  ualarm(200, 0);  /*https://www.man7.org/linux/man-pages/man3/ualarm.3.html*/

  /* Check the flag once in a while to see when to quit. */
  while (keep_going)
    do_stuff ();

  return EXIT_SUCCESS;
}


/*  sample output:

0: Doing stuff while waiting for alarm....
1: Doing stuff while waiting for alarm....
2: Doing stuff while waiting for alarm....
3: Doing stuff while waiting for alarm....
4: Doing stuff while waiting for alarm....
5: Doing stuff while waiting for alarm....
6: Doing stuff while waiting for alarm....
7: Doing stuff while waiting for alarm....
8: Doing stuff while waiting for alarm....
9: Doing stuff while waiting for alarm....
10: Doing stuff while waiting for alarm....
11: Doing stuff while waiting for alarm....
12: Doing stuff while waiting for alarm....
13: Doing stuff while waiting for alarm....
14: Doing stuff while waiting for alarm....
15: Doing stuff while waiting for alarm....
16: Doing stuff while waiting for alarm....
17: Doing stuff while waiting for alarm....
18: Doing stuff while waiting for alarm....
19: Doing stuff while waiting for alarm....
20: Doing stuff while waiting for alarm....
21: Doing stuff while waiting for alarm....
22: Doing stuff while waiting for alarm....
23: Doing stuff while waiting for alarm....
24: Doing stuff while waiting for alarm....
25: Doing stuff while waiting for alarm....
26: Doing stuff while waiting for alarm....
27: Doing stuff while waiting for alarm....
28: Doing stuff while waiting for alarm....
29: Doing stuff while waiting for alarm....
30: Doing stuff while waiting for alarm....
31: Doing stuff while waiting for alarm....
32: Doing stuff while waiting for alarm....
33: Doing stuff while waiting for alarm....
34: Doing stuff while waiting for alarm....
35: Doing stuff while waiting for alarm....
36: Doing stuff while waiting for alarm....
37: Doing stuff while waiting for alarm....
38: Doing stuff while waiting for alarm....
39: Doing stuff while waiting for alarm....
40: Doing stuff while waiting for alarm....
41: Doing stuff while waiting for alarm....
42: Doing stuff while waiting for alarm....
43: Doing stuff while waiting for alarm....
44: Doing stuff while waiting for alarm....
45: Doing stuff while waiting for alarm....
46: Doing stuff while waiting for alarm....
47: Doing stuff while waiting for alarm....
48: Doing stuff while waiting for alarm....
49: Doing stuff while waiting for alarm....
50: Doing stuff while waiting for alarm....
51: Doing stuff while waiting for alarm....
52: Doing stuff while waiting for alarm....
53: Doing stuff while waiting for alarm....
54: Doing stuff while waiting for alarm....
55: Doing stuff while waiting for alarm....
56: Doing stuff while waiting for alarm....
57: Doing stuff while waiting for alarm....
58: Doing stuff while waiting for alarm....
59: Doing stuff while waiting for alarm....
60: Doing stuff while waiting for alarm....
61: Doing stuff while waiting for alarm....
62: Doing stuff while waiting for alarm....
63: Doing stuff while waiting for alarm....
64: Doing stuff while waiting for alarm....
65: Doing stuff while waiting for alarm....
66: Doing stuff while waiting for alarm....
67: Doing stuff while waiting for alarm....
68: Doing stuff while waiting for alarm....
69: Doing stuff while waiting for alarm....
70: Doing stuff while waiting for alarm....
71: Doing stuff while waiting for alarm....
72: Doing stuff while waiting for alarm....
73: Doing stuff while waiting for alarm....
74: Doing stuff while waiting for alarm....
75: Doing stuff while waiting for alarm....
76: Doing stuff while waiting for alarm....
77: Doing stuff while waiting for alarm....
78: Doing stuff while waiting for alarm....
79: Doing stuff while waiting for alarm....
80: Doing stuff while waiting for alarm....
81: Doing stuff while waiting for alarm....
82: Doing stuff while waiting for alarm....
83: Doing stuff while waiting for alarm....
84: Doing stuff while waiting for alarm....
85: Doing stuff while waiting for alarm....
86: Doing stuff while waiting for alarm....
87: Doing stuff while waiting for alarm....
88: Doing stuff while waiting for alarm....
89: Doing stuff while waiting for alarm....
90: Doing stuff while waiting for alarm....
91: Doing stuff while waiting for alarm....
92: Doing stuff while waiting for alarm....
93: Doing stuf
ALARM!!!
f while waiting for alarm....

gcc -std=c11 -O2 -Wall -pedantic main.cpp && ./a.out
Compile, link and run...
Share!

*/
